-- SequenceNumbers schema

-- !Ups
CREATE TABLE SEQUENCE_NUMBERS (
  `PERSITENCE_ID` VARCHAR(254) NOT NULL PRIMARY KEY,
  `SEQUENCE_NUMBER` BIGINT NOT NULL
);

-- !Downs
DROP TABLE SEQUENCE_NUMBERS;

-- Shipments schema

-- !Ups
CREATE TABLE SHIPMENTS (
  `ID` VARCHAR(254) NOT NULL PRIMARY KEY,
  `VERSION` BIGINT NOT NULL,
  `TIME_ADDED` TEXT NOT NULL,
  `TIME_MODIFIED` TEXT,
  `STATE` TEXT NOT NULL,
  `COURIER_NAME` TEXT NOT NULL,
  `TRACKING_NUMBER` TEXT NOT NULL,
  `ORIGIN_CENTRE_ID` TEXT NOT NULL,
  `ORIGIN_LOCATION_ID` TEXT NOT NULL,
  `DESTINATION_CENTRE_ID` TEXT NOT NULL,
  `DESTINATION_LOCATION_ID` TEXT NOT NULL,
  `TIME_PACKED` TEXT,
  `TIME_SENT` TEXT,
  `TIME_RECEIVED` TEXT,
  `TIME_UNPACKED` TEXT,
  `TIME_COMPLETED` TEXT
);

-- !Downs
DROP TABLE SHIPMENTS;
