-- SequenceNumbers schema

-- !Ups
CREATE TABLE SEQUENCE_NUMBERS (
  `PERSITENCE_ID` VARCHAR(254) NOT NULL PRIMARY KEY,
  `SEQUENCE_NUMBER` BIGINT NOT NULL
);

-- !Downs
DROP TABLE SEQUENCE_NUMBERS;

-- Shipments schema

-- !Ups
create table `SHIPMENTS` (
  `ID` VARCHAR(254) NOT NULL PRIMARY KEY,
  `VERSION` BIGINT NOT NULL,
  `TIME_ADDED` TEXT NOT NULL,
  `TIME_MODIFIED` TEXT,
  `STATE` TEXT NOT NULL,
  `COURIER_NAME` TEXT NOT NULL,
  `TRACKING_NUMBER` TEXT NOT NULL,
  `ORIGIN_CENTRE_ID` TEXT NOT NULL,
  `ORIGIN_CENTRE_SLUG` TEXT NOT NULL,
  `ORIGIN_CENTRE_NAME` TEXT NOT NULL,
  `ORIGIN_LOCATION_ID` TEXT NOT NULL,
  `ORIGIN_LOCATION_SLUG` TEXT NOT NULL,
  `ORIGIN_LOCATION_NAME` TEXT NOT NULL,
  `DESTINATION_CENTRE_ID` TEXT NOT NULL,
  `DESTINATION_CENTRE_SLUG` TEXT NOT NULL,
  `DESTINATION_CENTRE_NAME` TEXT NOT NULL,
  `DESTINATION_LOCATION_ID` TEXT NOT NULL,
  `DESTINATION_LOCATION_SLUG` TEXT NOT NULL,
  `DESTINATION_LOCATION_NAME` TEXT NOT NULL,
  `TIME_PACKED` TEXT,
  `TIME_SENT` TEXT,
  `TIME_RECEIVED` TEXT,
  `TIME_UNPACKED` TEXT,
  `TIME_COMPLETED` TEXT,
  `SPECIMEN_COUNT` INTEGER NOT NULL,
  `PRESENT_SPECIMEN_COUNT` INTEGER NOT NULL,
  `CONTAINER_COUNT` INTEGER NOT NULL);

-- !Downs
DROP TABLE SHIPMENTS;

-- ShipmentSpecimens schema

-- !Ups
CREATE TABLE SHIPMENT_SPECIMENS (
  `ID` VARCHAR(254) NOT NULL PRIMARY KEY,
  `VERSION` BIGINT NOT NULL,
  `TIME_ADDED` TEXT NOT NULL,
  `TIME_MODIFIED` TEXT,
  `SHIPMENT_ID` VARCHAR(254) NOT NULL,
  `SPECIMEN_ID` VARCHAR(254) NOT NULL,
  `STATE` TEXT NOT NULL,
  `SHIPMENT_CONTAINER_ID` TEXT
);

ALTER TABLE SHIPMENT_SPECIMENS
  ADD CONSTRAINT `shipment_id`
  FOREIGN KEY(`SHIPMENT_ID`)
  REFERENCES `SHIPMENTS`(`ID`)
  ON UPDATE NO ACTION
  ON DELETE CASCADE;

-- !Downs
DROP TABLE SHIPMENT_SPECIMENS;
