-- SequenceNumbers schema

-- !Ups
CREATE TABLE sequence_numbers (
  `PERSITENCE_ID` VARCHAR(254) NOT NULL PRIMARY KEY,
  `SEQUENCE_NUMBER` BIGINT NOT NULL
);

-- !Downs
DROP TABLE sequence_numbers;

-- Shipments schema

-- !Ups
CREATE TABLE shipments (
  "ID" VARCHAR NOT NULL PRIMARY KEY,
  "VERSION" BIGINT NOT NULL,
  "TIME_ADDED" VARCHAR NOT NULL,
  "TIME_MODIFIED" VARCHAR,
  "STATE" VARCHAR NOT NULL,
  "COURIER_NAME" VARCHAR NOT NULL,
  "TRACKING_NUMBER" VARCHAR NOT NULL,
  "ORIGIN_CENTRE_ID" VARCHAR NOT NULL,
  "ORIGIN_CENTRE_SLUG" VARCHAR NOT NULL,
  "ORIGIN_CENTRE_NAME" VARCHAR NOT NULL,
  "ORIGIN_LOCATION_ID" VARCHAR NOT NULL,
  "ORIGIN_LOCATION_SLUG" VARCHAR NOT NULL,
  "ORIGIN_LOCATION_NAME" VARCHAR NOT NULL,
  "DESTINATION_CENTRE_ID" VARCHAR NOT NULL,
  "DESTINATION_CENTRE_SLUG" VARCHAR NOT NULL,
  "DESTINATION_CENTRE_NAME" VARCHAR NOT NULL,
  "DESTINATION_LOCATION_ID" VARCHAR NOT NULL,
  "DESTINATION_LOCATION_SLUG" VARCHAR NOT NULL,
  "DESTINATION_LOCATION_NAME" VARCHAR NOT NULL,
  "TIME_PACKED" VARCHAR,
  "TIME_SENT" VARCHAR,
  "TIME_RECEIVED" VARCHAR,
  "TIME_UNPACKED" VARCHAR,
  "TIME_COMPLETED" VARCHAR,
  "SPECIMEN_COUNT" INTEGER NOT NULL,
  "PRESENT_SPECIMEN_COUNT" INTEGER NOT NULL,
  "CONTAINER_COUNT" INTEGER NOT NULL
);

-- !Downs
DROP TABLE shipments;

-- ShipmentSpecimens schema

-- !Ups
CREATE TABLE shipment_specmens (
  `ID` VARCHAR(254) NOT NULL PRIMARY KEY,
  `VERSION` BIGINT NOT NULL,
  `TIME_ADDED` TEXT NOT NULL,
  `TIME_MODIFIED` TEXT,
  `SHIPMENT_ID` VARCHAR NOT NULL,
  `SPECIMEN_ID` TEXT NOT NULL,
  `STATE` TEXT NOT NULL,
  `SHIPMENT_CONTAINER_ID` TEXT,
  PRIMARY KEY (ID)
);

ALTER TABLE shipment_specmens
  ADD CONSTRAINT "shipment_id" FOREIGN KEY("SHIPMENT_ID")
  REFERENCES "SHIPMENTS"("ID")
  ON UPDATE NO ACTION
  ON DELETE CASCADE;

-- !Downs
DROP TABLE shipment_specimens;
