# Use container-based infrastructure
sudo: required
dist: trusty

matrix:
  include:
    - language: scala
      jdk: oraclejdk8
      scala: 2.13.1
      before_cache:
        # Cleanup the cached directories to avoid unnecessary cache updates
        - find $HOME/.ivy2/cache -name "ivydata-*.properties" -print -delete
        - find $HOME/.sbt        -name "*.lock"               -print -delete
      cache:
        directories:
          - $HOME/.ivy2/cache
          - $HOME/.sbt/boot/
      script:
        - cp conf/logback-test.xml.template conf/logback-test.xml
        - sbt ++$TRAVIS_SCALA_VERSION test:compile
        - sbt -Dfile.encoding=UTF8 -J-XX:ReservedCodeCacheSize=256M ++$TRAVIS_SCALA_VERSION clean coverage "test"
      after_success:
        - sbt ++$TRAVIS_SCALA_VERSION coverageReport coveralls

branches:
  only:
  - master
  - development
